name: RegionBackup
version: '${project.version}'
main: com.github.bbugsco.regionbackup.RegionBackup
api-version: '1.20'
author: bbugsco

commands:
  regionbackup:
    description: command for debug purposes, best not to use unless necessary
    aliases:
      - debug_forcebackup
      - debug_clearactiveregions
      - debug_showactiveregions
      - debug_updateactiveregions
    permission: regionbackup.command
    usage: /regionbackup
permissions:
  regionbackup.command:
    default: op
    description: allows for regionbackup command